apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 9393
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  ports:
  - port: 80
    targetPort: 9393

  selector:
    app: gitlab
